PRAGMA foreign_keys = ON;

ALTER TABLE projects ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'draft';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS featured_order INTEGER;

ALTER TABLE services ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'draft';
ALTER TABLE services ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS featured_order INTEGER;

ALTER TABLE certifications ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'draft';
ALTER TABLE certifications ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE certifications ADD COLUMN IF NOT EXISTS featured_order INTEGER;
ALTER TABLE certifications ADD COLUMN IF NOT EXISTS updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE labs ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE labs ADD COLUMN IF NOT EXISTS featured_order INTEGER;
ALTER TABLE labs ADD COLUMN IF NOT EXISTS updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE site_blocks ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'draft';
ALTER TABLE site_blocks ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE site_blocks ADD COLUMN IF NOT EXISTS featured_order INTEGER;
